# Generated by Django 4.2.7 on 2025-12-09 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishIdentification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to='fish_images/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True, help_text='Full URL to image in MinIO/S3', max_length=1000, null=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='fish_thumbnails/%Y/%m/%d/')),
                ('original_scientific_name', models.CharField(db_index=True, help_text='AI-predicted scientific name', max_length=255)),
                ('original_indonesian_name', models.CharField(db_index=True, help_text='AI-predicted Indonesian name', max_length=255)),
                ('original_english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_kelompok', models.CharField(blank=True, help_text='Original group/kelompok', max_length=100, null=True)),
                ('current_scientific_name', models.CharField(db_index=True, help_text='Current scientific name (may be corrected)', max_length=255)),
                ('current_indonesian_name', models.CharField(db_index=True, help_text='Current Indonesian name (may be corrected)', max_length=255)),
                ('current_english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_kelompok', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(help_text='AI confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('detection_box', models.JSONField(blank=True, help_text='Bounding box coordinates [x, y, width, height]', null=True)),
                ('detection_score', models.FloatField(blank=True, null=True)),
                ('kb_candidates', models.JSONField(blank=True, help_text='Knowledge base candidates used', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('corrected', 'Corrected by User'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_corrected', models.BooleanField(db_index=True, default=False, help_text='True if user corrected the identification')),
                ('correction_notes', models.TextField(blank=True, help_text='User notes on correction', null=True)),
                ('user_identifier', models.CharField(blank=True, db_index=True, help_text='User ID or session ID', max_length=255, null=True)),
                ('user_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrected_at', models.DateTimeField(blank=True, help_text='When user made correction', null=True)),
            ],
            options={
                'verbose_name': 'Fish Identification',
                'verbose_name_plural': 'Fish Identifications',
                'db_table': 'fish_identifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FishSpeciesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('indonesian_name', models.CharField(db_index=True, max_length=255)),
                ('english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kelompok', models.CharField(blank=True, max_length=100, null=True)),
                ('total_identifications', models.IntegerField(default=0)),
                ('correct_identifications', models.IntegerField(default=0, help_text='Verified as correct')),
                ('corrected_identifications', models.IntegerField(default=0, help_text='User corrected')),
                ('average_confidence', models.FloatField(default=0.0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Species Statistics',
                'verbose_name_plural': 'Species Statistics',
                'db_table': 'fish_species_statistics',
                'ordering': ['-total_identifications'],
            },
        ),
        migrations.CreateModel(
            name='FishIdentificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Field that was changed', max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='recognition.fishidentification')),
            ],
            options={
                'verbose_name': 'Identification History',
                'verbose_name_plural': 'Identification Histories',
                'db_table': 'fish_identification_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fishidentification',
            index=models.Index(fields=['-created_at'], name='fish_identi_created_7386f5_idx'),
        ),
        migrations.AddIndex(
            model_name='fishidentification',
            index=models.Index(fields=['status', '-created_at'], name='fish_identi_status_388e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='fishidentification',
            index=models.Index(fields=['current_indonesian_name'], name='fish_identi_current_912be7_idx'),
        ),
        migrations.AddIndex(
            model_name='fishidentification',
            index=models.Index(fields=['original_indonesian_name'], name='fish_identi_origina_6e3ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='fishidentification',
            index=models.Index(fields=['is_corrected'], name='fish_identi_is_corr_e60e68_idx'),
        ),
    ]
