# Generated by Django 4.2.7 on 2025-12-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishidentification',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Full URL to thumbnail in MinIO/S3', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fishidentification',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='fish_images/%Y/%m/%d/'),
        ),
    ]
