# Generated by Django 4.2.7 on 2025-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_fishidentification_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_indonesia', models.CharField(db_index=True, help_text='Nama Indonesia', max_length=255)),
                ('species_english', models.CharField(blank=True, help_text='Nama Inggris', max_length=255, null=True)),
                ('nama_latin', models.TextField(help_text='Nama Latin (scientific name)')),
                ('nama_daerah', models.TextField(blank=True, help_text='Nama daerah/lokal', null=True)),
                ('kelompok', models.CharField(blank=True, help_text='Kelompok ikan', max_length=100, null=True)),
                ('jenis_perairan', models.CharField(blank=True, choices=[('LAUT', 'Laut'), ('TAWAR', 'Tawar'), ('PAYAU', 'Payau'), ('LAUT, PAYAU', 'Laut & Payau'), ('LAUT, TAWAR', 'Laut & Tawar'), ('PAYAU, TAWAR', 'Payau & Tawar'), ('LAUT, PAYAU, TAWAR', 'Laut, Payau & Tawar')], max_length=50, null=True)),
                ('jenis_konsumsi', models.CharField(blank=True, choices=[('KONSUMSI', 'Konsumsi'), ('NON KONSUMSI', 'Non Konsumsi')], max_length=20, null=True)),
                ('jenis_hias', models.CharField(blank=True, choices=[('HIAS', 'Hias'), ('NON HIAS', 'Non Hias')], max_length=20, null=True)),
                ('jenis_dilindungi', models.CharField(blank=True, choices=[('YA', 'Ya'), ('TIDAK', 'Tidak')], max_length=10, null=True)),
                ('prioritas', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=10)),
                ('search_keywords', models.TextField(blank=True, help_text='Keywords untuk pencarian', null=True)),
                ('min_images', models.IntegerField(default=100, help_text='Minimum jumlah gambar untuk training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fish Master Data',
                'verbose_name_plural': 'Fish Master Data',
                'db_table': 'fish_master_data',
                'ordering': ['species_indonesia'],
                'indexes': [models.Index(fields=['species_indonesia'], name='fish_master_species_0f7e5b_idx'), models.Index(fields=['kelompok'], name='fish_master_kelompo_1f9777_idx'), models.Index(fields=['jenis_perairan'], name='fish_master_jenis_p_b64ee5_idx'), models.Index(fields=['prioritas'], name='fish_master_priorit_e43972_idx')],
            },
        ),
    ]
