"""
Django settings for fish_recognition_api project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-r()$vg*7$o&jd2#_5#7f-=jd5@9w^-l#8$w3yg*=6+3#0a3-8r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*'] if DEBUG else os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',  # Django Unfold must be before django.contrib.admin
    'unfold.contrib.filters',  # optional, if special filters are needed
    'unfold.contrib.forms',  # optional, if special form elements are needed
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',  # DRF Spectacular for API documentation
    'corsheaders',
    'channels',
    'recognition',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'fish_recognition_api.middleware.DisableCSRFForAPIMiddleware',  # Custom CSRF exempt for API
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fish_recognition_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fish_recognition_api.wsgi.application'
ASGI_APPLICATION = 'fish_recognition_api.asgi.application'

# Channels configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', 36379)))],
        },
    },
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
    "https://smart-mancing.hellodigi.id",
    "https://fish.hellodigi.id",
]

CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8001",
    "http://127.0.0.1:8001",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://smart-mancing.hellodigi.id",
    "https://fish.hellodigi.id",
]

# Disable CSRF for API endpoints (they use csrf_exempt decorator)
# This is needed because middleware checks before decorator
import re
CSRF_EXEMPT_URLS = [
    re.compile(r'^api/'),
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.getenv('DATABASE_URL'):
    # Use DATABASE_URL if provided (for Docker or production)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Use individual PostgreSQL settings or fallback to SQLite
    if os.getenv('POSTGRES_HOST'):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('POSTGRES_DB', 'fish_recognition'),
                'USER': os.getenv('POSTGRES_USER', 'fish_user'),
                'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'fish_password'),
                'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
                'PORT': os.getenv('POSTGRES_PORT', '5432'),
            }
        }
    else:
        # Fallback to SQLite for local development
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files - MinIO Storage
if os.getenv('MINIO_ENDPOINT'):
    # Use MinIO for media storage
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    AWS_ACCESS_KEY_ID = os.getenv('MINIO_ACCESS_KEY', os.getenv('MINIO_ROOT_USER', 'minioadmin'))
    AWS_SECRET_ACCESS_KEY = os.getenv('MINIO_SECRET_KEY', os.getenv('MINIO_ROOT_PASSWORD', 'minioadmin123'))
    AWS_STORAGE_BUCKET_NAME = os.getenv('MINIO_BUCKET_NAME', 'fish-media')
    AWS_S3_ENDPOINT_URL = f"http{'s' if os.getenv('MINIO_USE_SSL', 'False').lower() == 'true' else ''}://{os.getenv('MINIO_ENDPOINT')}"
    AWS_S3_USE_SSL = os.getenv('MINIO_USE_SSL', 'False').lower() == 'true'
    AWS_S3_VERIFY = False  # For self-signed certificates
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_REGION_NAME = 'us-east-1'  # MinIO default
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600
    
    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
else:
    # Fallback to local file storage
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Fish Recognition API',
    'DESCRIPTION': 'API for fish detection, classification, and recognition using AI models. Supports single and batch image processing with face detection, segmentation, and LLM-powered species verification.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SERVERS': [
        {'url': 'http://localhost:8001', 'description': 'Local development server'},
        {'url': 'https://smart-mancing.hellodigi.id', 'description': 'Production server'},
    ],
    'CONTACT': {
        'name': 'Fish Recognition API Team',
        'email': 'support@example.com',
    },
    'LICENSE': {
        'name': 'MIT',
    },
    'TAGS': [
        {'name': 'Recognition', 'description': 'Fish recognition and detection endpoints'},
        {'name': 'Health', 'description': 'Health check and system status'},
        {'name': 'Configuration', 'description': 'Model configuration and settings'},
        {'name': 'Identification', 'description': 'Fish identification history and management'},
        {'name': 'Correction', 'description': 'Manual correction and feedback'},
        {'name': 'Dataset', 'description': 'Dataset management and master data'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'tryItOutEnabled': True,
    },
    'PREPROCESSING_HOOKS': [],
    'POSTPROCESSING_HOOKS': [],
    'ENUM_NAME_OVERRIDES': {},
    'SERVE_AUTHENTICATION': None,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
}

# Fish Recognition Model Settings
FISH_MODEL_SETTINGS = {
    'CLASSIFICATION_MODEL': os.path.join(BASE_DIR.parent, 'models/classification/model.ckpt'),
    'CLASSIFICATION_DATABASE': os.path.join(BASE_DIR.parent, 'models/classification/database.pt'),
    'CLASSIFICATION_LABELS': os.path.join(BASE_DIR.parent, 'models/classification/labels.json'),
    'DETECTION_MODEL': os.path.join(BASE_DIR.parent, 'models/detection/model.ts'),
    'SEGMENTATION_MODEL': os.path.join(BASE_DIR.parent, 'models/segmentation/model.ts'),
    'FACE_DETECTION_MODEL': os.path.join(BASE_DIR.parent, 'models/face_detector/model.ts'),
    
    # Performance settings
    'DEVICE': 'cpu',  # or 'cuda' if available
    'BATCH_SIZE': 1,
    'CONFIDENCE_THRESHOLD': 0.5,
    'NMS_THRESHOLD': 0.3,
    'SEGMENTATION_THRESHOLD': 0.5,
    
    # Cache settings
    'ENABLE_MODEL_CACHING': True,
    'CACHE_TIMEOUT': 3600,  # 1 hour
}

# Ollama LLM Settings for enhanced fish classification
OLLAMA_URL = os.getenv('OLLAMA_URL', 'https://ollama.hellodigi.id')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'gemma3:27b')
LLM_ENABLED = os.getenv('LLM_ENABLED', 'True').lower() == 'true'
LLM_TIMEOUT = int(os.getenv('LLM_TIMEOUT', '30'))  # seconds

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'fish_api.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Django Unfold Configuration
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Fish Recognition",
    "SITE_HEADER": "Fish Recognition System",
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SITE_LOGO": None,
    "SITE_SYMBOL": "🐟",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "ENVIRONMENT": "fish_recognition_api.utils.environment_callback",
    "DASHBOARD_CALLBACK": "fish_recognition_api.utils.dashboard_callback",
    "THEME": "dark",
    "COLORS": {
        "primary": {
            "50": "220 252 231",
            "100": "187 247 208",
            "200": "134 239 172",
            "300": "74 222 128",
            "400": "34 197 94",
            "500": "22 163 74",
            "600": "21 128 61",
            "700": "22 101 52",
            "800": "22 78 42",
            "900": "20 64 36",
            "950": "5 30 16",
        },
    },
    "SITE_DROPDOWN": [
        {
            "icon": "diamond",
            "title": _("Home"),
            "link": lambda request: "/",
        },
        # ...
    ],
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇳🇱",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": lambda request: "/admin/",
                    },
                ],
            },
            {
                "title": _("Fish Identification"),
                "separator": True,
                # "collapsible": True,
                "items": [
                    {
                        "title": _("All Identifications"),
                        "icon": "visibility",
                        "link": lambda request: "/admin/recognition/fishidentification/",
                        "permission": lambda request: request.user.has_perm("recognition.view_fishidentification"),
                    },
                    {
                        "title": _("Pending Review"),
                        "icon": "pending_actions",
                        "link": lambda request: "/admin/recognition/fishidentification/?status__exact=pending",
                        "badge": lambda request: __import__('recognition.models', fromlist=['FishIdentification']).FishIdentification.objects.filter(status='pending').count(),
                        "permission": lambda request: request.user.has_perm("recognition.view_fishidentification"),
                    },
                    {
                        "title": _("Verified"),
                        "icon": "verified",
                        "link": lambda request: "/admin/recognition/fishidentification/?status__exact=verified",
                        "permission": lambda request: request.user.has_perm("recognition.view_fishidentification"),
                    },
                    {
                        "title": _("Rejected"),
                        "icon": "cancel",
                        "link": lambda request: "/admin/recognition/fishidentification/?status__exact=rejected",
                        "permission": lambda request: request.user.has_perm("recognition.view_fishidentification"),
                    },
                ],
            },
            {
                "title": _("Analytics"),
                "separator": True,
                # "collapsible": True,
                "items": [
                    {
                        "title": _("History"),
                        "icon": "history",
                        "link": lambda request: "/admin/recognition/fishidentificationhistory/",
                        "permission": lambda request: request.user.has_perm("recognition.view_fishidentificationhistory"),
                    },
                    {
                        "title": _("Species Statistics"),
                        "icon": "analytics",
                        "link": lambda request: "/admin/recognition/fishspeciesstatistics/",
                        "permission": lambda request: request.user.has_perm("recognition.view_fishspeciesstatistics"),
                    },
                ],
            },
            {
                "title": _("Master Data"),
                "separator": True,
                # "collapsible": True,
                "items": [
                    {
                        "title": _("Fish Species"),
                        "icon": "emoji_nature",
                        "link": lambda request: "/admin/recognition/fishmasterdata/",
                        "permission": lambda request: request.user.has_perm("recognition.view_fishmasterdata"),
                    },
                ],
            },
            {
                "title": _("Administration"),
                "separator": True,
                # "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": lambda request: "/admin/auth/user/",
                        "permission": lambda request: request.user.has_perm("auth.view_user"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": lambda request: "/admin/auth/group/",
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "recognition.fishidentification",
            ],
            "items": [
                {
                    "title": _("All"),
                    "icon": "list",
                    "link": lambda request: "/admin/recognition/fishidentification/",
                },
                {
                    "title": _("Pending"),
                    "icon": "pending",
                    "link": lambda request: "/admin/recognition/fishidentification/?status__exact=pending",
                },
                {
                    "title": _("Verified"),
                    "icon": "check_circle",
                    "link": lambda request: "/admin/recognition/fishidentification/?status__exact=verified",
                },
            ],
        },
    ],
}

